[project]
name = "ner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi==0.95.0",
    "numpy==1.24.2",
    "pyyaml==6.0",
    "transformers==4.29.2",
    "uvicorn==0.22.0",
]
